name: Remove Dependabot labels

on:
  pull_request:
    types: [opened, labeled]
  workflow_dispatch:

jobs:
  clean-labels:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    if: github.event_name == 'workflow_dispatch' || github.actor == 'dependabot[bot]'
    steps:
      - name: Remove labels
        run: |
          gh api -X DELETE repos/${{ github.repository }}/labels/github-actions || true
          gh api -X DELETE repos/${{ github.repository }}/labels/dependencies || true
          gh api -X DELETE repos/${{ github.repository }}/labels/javascript || true
          gh api -X DELETE repos/${{ github.repository }}/labels/security || true
          gh api -X DELETE repos/${{ github.repository }}/labels/python || true
          gh api -X DELETE repos/${{ github.repository }}/labels/dotnet || true
          gh api -X DELETE repos/${{ github.repository }}/labels/ruby || true
          gh api -X DELETE repos/${{ github.repository }}/labels/rust || true
          gh api -X DELETE repos/${{ github.repository }}/labels/php || true
          gh api -X DELETE repos/${{ github.repository }}/labels/go || true
        env:
          GH_TOKEN: ${{ github.token }}
